### ISSUE TITLE
Decoding into nullable custom types fails when OID is registered

### ISSUE THREAD

**Issue by henryperson** [jackc/pgtype#103]
Say you have the following types:
```
type A struct {
    Value int
    B *B
}

type B struct {
    Text string
}
```
and assume their corresponding types are registered in your database. `A.B` is a pointer field because it's `NULL`able in your database.

In `A`'s `DecodeBinary` function, you will have some line of code resembling:
```
pgtype.CompositeFields{&dst.Value, &dst.B}.DecodeBinary(ci, src)
```
I believe if this were working correctly, you could be decoding a row where `B` was `NULL` and you would not run into an error. Instead, you end up in `B`'s `DecodeBinary` method with `src == nil`, which I understand from [this example](https://pkg.go.dev/github.com/jackc/pgtype#example-package-CustomCompositeTypes) is not intended to happen.

It seems like a fix was intended for a problem like this in #10. However, it looks like that was meant only for types where the OID was not registered. In this case, the OID is registered and (despite the type being `**B`) pgtype is able to find the OID and thus plans to decode it normally using a `scanPlanDataTypeAssignTo`, rather than using reflection, which would cause it to use the fix from the PR above.

Am I right that this is unintended behavior? If I'm wrong, how is one supposed to decode a `NULL` field into a pointer?

Thanks for your time.

**Comment by jackc** [comment]
I think that case should work, but I don't think it is tested anywhere. Do you have a test case that produces an error?

**Comment by henryperson** [comment]
Here is a contrived example that shows the error. The overall structure is that we have one table, `complex`, and that table has a normal int type and an nullable custom type called `Optional`. I have two examples, one where I scan a `NULL` into an `*Optional`, and the other where I scan a non-NULL value into an `*Optional`. Both fail, though you'll have to comment out the first to see the second. I didn't actually know the second one fails. That seems like a bug as well.

The output of the first example is
```
Error: can't scan into dest[0]: NULL values can't be decoded. Scan into a &*Optional to handle NULLs
```
And the output of the second example is
```
Error: can't scan into dest[0]: cannot assign &{1 2} to **main.Optional
```
It's weird because in the `NULL` case, it's actually getting into the `DecodeBinary` function, but in the second case it's not.

```go
package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"runtime"

	"github.com/jackc/pgtype"
	"github.com/jackc/pgx/v4"
)

type Optional struct {
	a int
	b int
}

type Complex struct {
	n   int
	opt *Optional
}

// These functions make Optional implement pgtype.Value, though they are not used in this example.
func (dst *Optional) Set(src interface{}) error {
	return fmt.Errorf("cannot convert %v to Optional", src)
}
func (dst *Optional) Get() interface{} {
	return dst
}
func (src *Optional) AssignTo(dst interface{}) error {
	return fmt.Errorf("cannot assign %v to %T", src, dst)
}

// EncodeBinary encodes an Optional into binary.
func (src *Optional) EncodeBinary(ci *pgtype.ConnInfo, buf []byte) ([]byte, error) {
	if src == nil {
		return nil, nil
	}

	b, err := (&pgtype.CompositeFields{
		&pgtype.Int8{Int: int64(src.a), Status: pgtype.Present},
		&pgtype.Int8{Int: int64(src.b), Status: pgtype.Present},
	}).EncodeBinary(ci, buf)
	if err != nil {
		return nil, fmt.Errorf("could not encode Optional: %w", err)
	}
	return b, nil
}

func (dst *Optional) DecodeBinary(ci *pgtype.ConnInfo, src []byte) error {
	if src == nil {
		return errors.New("NULL values can't be decoded. Scan into a &*Optional to handle NULLs")
	}

	err := (pgtype.CompositeFields{&dst.a, &dst.b}).DecodeBinary(ci, src)
	if err != nil {
		return fmt.Errorf("could not decode composite fields: %w", err)
	}
	return nil
}

func main() {
	// This, combined with the runtime.Goexit() in check(err), will ensure defers are honored in
	// case an error is hit.
	defer os.Exit(0)

	bg := context.Background()

	// Config, you may need to change these values.
	user := os.Getenv("USER")
	password := ""
	host := "localhost"

	// Connect to postgres.
	pgUrl := fmt.Sprintf("postgres://%v:%v@%v:5432/%v", user, password, host, "postgres")
	conn, err := pgx.Connect(bg, pgUrl)
	check(err)
	defer conn.Close(bg)

	// Create test database.
	_, err = conn.Exec(bg, "CREATE DATABASE pgx_test")
	check(err)
	defer conn.Exec(bg, "DROP DATABASE pgx_test")

	// Using an in line function so defers are sequenced correctly.
	func() {
		defer catchPanic()

		// Connect to newly created database.
		url := fmt.Sprintf("postgres://%v:%v@%v:5432/%v", user, password, host, "pgx_test")
		testDB, err := pgx.Connect(bg, url)
		check(err)
		defer testDB.Close(bg)

		// Create relevant types and tables.
		_, err = testDB.Exec(bg, "CREATE TYPE optional AS (a bigint, b bigint)")
		check(err)
		_, err = testDB.Exec(bg, "CREATE TABLE complex (n bigint, opt optional)")
		check(err)

		// Register Optional's OID. Otherwise we cannot scan it.
		var optionalOID uint32
		err = testDB.QueryRow(bg, `select 'optional'::regtype::oid`).Scan(&optionalOID)
		check(err)
		testDB.ConnInfo().RegisterDataType(pgtype.DataType{Value: &Optional{}, Name: "optional", OID: optionalOID})

		compNil := Complex{n: 4, opt: nil}
		_, err = testDB.Exec(bg, "INSERT INTO complex(n, opt) VALUES ($1, $2)", compNil.n, compNil.opt)
		check(err)
		var oNil *Optional
		err = testDB.QueryRow(bg, "SELECT opt FROM complex WHERE n=$1 LIMIT 1", compNil.n).Scan(&oNil)
		check(err)
		fmt.Println("oNil:", oNil)

		comp := Complex{n: 3, opt: &Optional{a: 1, b: 2}}
		_, err = testDB.Exec(bg, "INSERT INTO complex(n, opt) VALUES ($1, $2)", comp.n, comp.opt)
		check(err)
		var o *Optional
		err = testDB.QueryRow(bg, "SELECT opt FROM complex WHERE n=$1 LIMIT 1", comp.n).Scan(&o)
		check(err)
		fmt.Println("o:", o)
	}()
}

func check(err error) {
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		runtime.Goexit() // see defer statement at the start of main.
	}
}

func catchPanic() {
	if err := recover(); err != nil {
		fmt.Println(err)
	}
}

```

Let me know if I should reformat this in some way to make it easier to run. I've tried to make it as easy as possible to copy paste this and have it work.

**Comment by jackc** [comment]
I think I have figured out the problem.

First, any type registered with `*ConnInfo.RegisterDataType` must be able to decode `NULL`. Registered types are designed to decode whatever comes from the database and then `AssignTo` the scan target. `AssignTo` typically should handle `NULL` with `pgtype.NullAssignTo`. So if you want a non-nullable `T` for application use and you want to register the type you will need a `NullT` to register. You can see this in `pgtype` itself with `OID` and `OIDValue` types. Sadly, this requirement doesn't appear to have been documented anywhere. 🤷

Second, if you don't register the type, then you are stuck using the text format. So in your example above if we remove the `RegisterDataType` then the second select will fail unless you add `DecodeText` or force the binary protocol with `pgx.QueryResultFormats{pgx.BinaryFormatCode}` (like the CustomCompositeTypes example does).

I don't see any simpler way around these constraints. I think the solution is to document that any type registered with `*ConnInfo.RegisterDataType` must be able to decode `NULL`.

**Comment by henryperson** [comment]
I'm having a bit of trouble understanding what changes this would mean making to the example I wrote above. I could make `Optional.DecodeBinary` return `nil` when it sees `src == nil` but I can't piece together the rest, especially the change to `AssignTo`.

It seems like you're proposing something like the following change to `AssignTo`:
```go
func (src *Optional) AssignTo(dst interface{}) error {
        if src == nil {
		dst = nil
	} else if optional, ok := dst.(**Optional); ok {
		*optional = src
		return nil
	}
	return fmt.Errorf("cannot assign %v to %T", src, dst)
}
```

However this doesn't work, as `src` will never be `nil` (or it's not in my example, which is when I'd expect it to be). Other than this, I'm not really sure how to tell if you're trying to `AssignTo` from a `NULL` source. I guess you could check that `src` is the zero value of its type, but in the case where your zero value and `nil` are meaningfully different, you'd be out of luck.

**Comment by jackc** [comment]
For `AssignTo` to handle `nil`, the struct it is a method of needs to be able to represent `nil` (e.g. have a `Status` field). That's what I meant when saying that anything registered with `RegisterDataType` must support nil.

The smallest change to get your example to work is to not register your optional type but to force the query to use the binary protocol with `pgx.QueryResultFormats{pgx.BinaryFormatCode}`.

**Comment by henryperson** [comment]
Ok this makes sense. For various reasons my use case forces me to register the types, but having `AssignTo` handle the `nil` via making it clear through the object when it's supposed to be `nil` is satisfactory and works for me. Feel free to close.
