### ISSUE TITLE
Parsing nullable DB value to sql.Scanner fails

### ISSUE THREAD

**Issue by jan-dubsky** [jackc/pgtype#105]
I have a custom type `type A struct{}` implementing `sql.Scanner` interface and supporting it's parsing from `VARCHAR` database field:
```
// Example code
func (a *A) Scan(src interface{}) error {
	str, ok := src.(string)
	if !ok {
		return fmt.Errorf("cannot parse A from type %T", src)
	}

	*a = ParseString(str)
	return nil
}
```
Naturally, the method `Scan` must have a pointer receiver, so it can modify the actual value of the custom type. If I ask `pgx` to parse my type `A`, everything works as expected. I pass `*A` to the `Scan` method of `pgx.Rows`, the`Scanner` interface is correctly recognized and the value is parsed using the `Scan` method. 

Unfortunately the situation is different when my field in the database is` NULLABLE`. In such case, I need to parse a pointer to my type `A` to be able to special case the NULL value. Consequently, the value I have to pass to `Scan` method is `**A` (one pointer for `pgx.Scan` to allow parsing and the `*A` is the value I want to scan). In other words, the type `pgx.Scan` can see is `*sql.Scanner`. And this type is not recognized as a custom type implementing `Scan` method. Instead, the parsing fails with an error that it's not possible to parse my type because it's unknown.

**Comment by jackc** [comment]
I don't think the `sql.Scanner` interface works that way. Take a look at `sql.NullString` for an example. They have a `Valid` field to handle `NULL`. I don't think `database/sql` tries to handle `**T`.

**Comment by jan-dubsky** [comment]
Thank you for reference. I still don't consider the behaviour of the `pgx.Scanner` interface to be optimal, as it's inconsistent with basic type parsing. For example with `string`, you can forward `**string` to the `pgx` library and `null` value will correctly parsed to `*string` as `nil`. But I understand you are not the author of the interface so you shouldn't be the one who will change its meaning. Thank you for pointing me out how to parse custom types.
