### ISSUE TITLE
Cannot use pgtype.DataType in ConnInfo.RegisterDataType

### ISSUE THREAD

**Issue by opslock-benjamin** [jackc/pgtype#109]
```
	UUIDType := pgtype.DataType{
		Value: &pgtypeuuid.UUID{},
		Name:  "uuid",
		OID:   pgtype.UUIDOID,
	}

	conn.ConnInfo.RegisterDataType(UUIDType)
```

**cannot use UUIDType (variable of type pgtype.DataType) as pgtype.DataType value in argument to conn.ConnInfo.RegisterDataType**

Any idea why this doesn't work?

**Comment by jackc** [comment]
It looks correct to me. But if I had to guess I'd say module versions is causing a problem. Check if pgtype is github.com/jackc/pgtype. You might have the old version that was in github.com/jackc/pgx/pgtype.

**Comment by opslock-benjamin** [comment]
if you don't explicitly import v4 then golang/vscode auto imports regular pgx.

```
import (
  pgx4 "github.com/jackc/pgx/v4
)
```

**Comment by bbernays** [comment]
I think the issue is it should be `conn.ConnInfo()` not `conn.ConnInfo` so the entire line would be:
```
	conn.ConnInfo().RegisterDataType(UUIDType)
```
