### ISSUE TITLE
More efficient API for creating TextArray (probably other arrays too?)

### ISSUE THREAD

**Issue by alex** [jackc/pgtype#11]
Right now I've got code like:

```go
ids := []string{}
for obj := range objs {
    ids = append(ids, obj.id)
}

idsArray := &pgtype.TextArray{}
idsArray.Set(ids)
tx.Query(ctx, `SELECT * FROM TABLE WHERE id = ANY($1)`, idsArray)
```

The `TextArray` API here is relatively inefficient because it requires allocating a new slice of `[]Text`. I can manually create an instance, but this requires knowing how to populate the `Dimensions` field. Worse, there's no easy way to reuse the allocated memory, if I'm doing multiple queries.

I think the right solution here would be if `TextArray.Set()` supported intialization from `[]pgtype.Text`.

I believe this would be a straightforward addition to the API, and I'd be happy to send a PR if you're interested. The code probably looks something like:

```go
case []Text:
    if value == nil {
        *dst = TextArray{Status: Null}
    } else if len(value) == 0 {
        *dst = TextArray{Status: Present}
    } else {
        *dst = TextArray{Elements: value, Dimensions: []ArrayDimension{{Length: int32(len(value)), LowerBound: 1}}, Status: Present}
    }
```
inserted at https://github.com/jackc/pgtype/blob/master/text_array.go#L44

**Comment by jackc** [comment]
As far as ergonomics go, you shouldn't have to use `TextArray` directly at all unless you have nulls or different array dimensions.

This should work:

```go
ids := []string{}
for obj := range objs {
    ids = append(ids, obj.id)
}

tx.Query(ctx, `SELECT * FROM TABLE WHERE id = ANY($1)`, ids)
```

Does the above code work? If so then the question is if it still suffers from the performance penalty you describe.

**Comment by alex** [comment]
Unless I've done something badly wrong, running with a `[]string` produces `sql: converting argument $1 type: unsupported type []string, a slice of string`

**Comment by alex** [comment]
Ahhh, please ignore that, my application uses `pgx` directly in some places and via `sqlx` in other places -- that error is coming from the `sqlx` portion.

Yes, using `[]string` directly works, however unless I've badly mis-read the source code for pgx/pgtype, it'll produce the allocation pattern I described.

**Comment by jackc** [comment]
The array types are of necessity fairly heavy because of needing to support null elements and because PostgreSQL supports multi-dimensional arrays with arbitrary beginning and ending indexes.

The change you suggested to Array.Set is fine -- probably the change would be made to `typed_array.go.erb` so it can be used in all the array types.

However, I suspect the vast majority of PostgreSQL array usage is serializing a traditional slice like `[]string`. And this makes me wonder if there is an even better way optimize that particular usage pattern.

**Comment by alex** [comment]
How important is it to maintain the existing public API on these types?

If you made `Elements` private, I could imagine each of these types having two fields `[]Text` and `[]string`, and it always being that one of them was `nil`.

That's the simplest thing I could possibly imagine working.

**Comment by jackc** [comment]
That would make sense, but the API can't be changed for existing types without a major release (and this change would cascade to pgx as well).

But it might make sense to create new types that are optimized for the simple case. Something like `type SimpleTextArray []string` that implemented the pgtype interfaces.

**Comment by alex** [comment]
That makes sense -- pgx would then need to map certain OIDs to those types for it to actually work, right?

Do OIDs from PostgreSQL give you enough info to know which type to use?

**Comment by jackc** [comment]
Yes and yes.

However, only one pgtype can be the default handler for an OID. So using these new types would have to be on an opt-in basis.

This could be done per-query by type conversion.

```go
tx.Query(ctx, `SELECT * FROM TABLE WHERE id = ANY($1)`, SimpleTextArray(ids))
```

Or to make it the new default `ConnInfo.RegisterDataType` could be used.
