### ISSUE TITLE
Unable to perform null-handling with Runes

### ISSUE THREAD

**Issue by DarcInc** [jackc/pgtype#123]
I have a simple test program that creates two rows in a table.  One with all the fields populated and one with all the fields null.  The fields are all basic types like integers, strings, characters, etc.  When I try to return a possibly null database `char`, it's my understanding it has to come back as a Go `rune`.  When I call scan, I get an error:

```sh
can't scan into dest[4]: unable to assign to *int32
```

The SQL to set this up and the go code is fairly straightforward.  

```sql
CREATE TABLE basic_types
(
    id            BIGSERIAL PRIMARY KEY,
    small_int     INT2,
    default_int   INT,
    medium_int    INT4,
    large_int     INT8,
    regular_char  CHAR
);

INSERT INTO basic_types (small_int, default_int, medium_int, large_int, regular_char)
VALUES (5, 5, 5, 5, 'A');

INSERT INTO basic_types DEFAULT VALUES ;
```

```go
var smallInt *int16
var defaultInt *int32
var mediumInt *int32
var largeInt *int64
var regularChar *rune

err := rows.Scan(&smallInt, &defaultInt, &mediumInt, &largeInt, &regularChar)
if err != nil {
	log.Printf("Failed to scan basic_types: %v", err)
}
```

The punch line is when I run it through a debugger and trace the execution, I wind up failing in the default switch case in `Text#AssignTo(interface{}) error`, resulting in a call to GetAssignToDstType.  I think what's happening is the destination's type is no longer the *rune in the code above but a *int32, and there's no good way to convert "A" to int32.  I could be wrong about this.  I also suspect we shouldn't be in the `Text` version of `AssignTo` but instead should be in the `BPChar` version, but I could also be wrong about that.

```go
func (src *Text) AssignTo(dst interface{}) error {
	switch src.Status {
	case Present:
		switch v := dst.(type) {
		case *string:
			*v = src.String
			return nil
		case *[]byte:
			*v = make([]byte, len(src.String))
			copy(*v, src.String)
			return nil
		default:
			if nextDst, retry := GetAssignToDstType(dst); retry {
				return src.AssignTo(nextDst)
			}
			return fmt.Errorf("unable to assign to %T", dst)
		}
	case Null:
		return NullAssignTo(dst)
	}

	return fmt.Errorf("cannot decode %#v into %T", src, dst)
}
```

Here's what I found, walking it through the debugger:

Tracing it through the debugger, `pgx.Rows#Scan(...interface{}) error` sets up the scan plan for that column as a `*github.com/jackc/pgtype.scanPlanDataTypeAssignTo` with Value, textDecoder, binaryDecoder all equal to `*github.com/jackc/pgtype.BPChar`, Name of 'bpchar' and an OID of 1042. 

`pgx.Rows#Scan(...interface{})` winds up calling `Scan` for `scanPlanDataTypeAssignTo`.  In that method we call `dt.textDecoderDecodeText` and get back the right character value stored in the database.  dt.Value still points to an instance of `GitHub.com/jackc/pgtype.BPChar`.  

`scanPlanDataTypeAssingTo#Scan` then calls `dt.Value.AssignTo(dst)`.  The dt.Status is Present.  However, in the switch statement in PBChar#AssignTo(interface{}), our dst.(type) no type entry is found, so the case *rune branch is skipped:

```go
func (src *BPChar) AssignTo(dst interface{}) error {
	if src.Status == Present {
		switch v := dst.(type) {
		case *rune:
			runes := []rune(src.String)
			if len(runes) == 1 {
				*v = runes[0]
				return nil
			}
		}
	}
	return (*Text)(src).AssignTo(dst)
}
```

That means we fall into the `Text#AssignTo` method call at the bottom.  In that method we don't hit the switch case for *string or *[]byte types and go into the default case.  That means we call `Text#GetAssignToDestType(dst interface{}) (interface{}, bool)`. 

In that function, the dstVal.Kind() returns a type of unsafe pointer.  We call back into `Text#AssignTo` and again we fall into the default cause of the switch statement, calling back into GetAssignToDstType.  This time our type is an `int32`.  We call toInteface with a dstPtr as the unsafe pointer for our destination (originally a `*rune`) and source pointer to a string.  That returns false, so we hit the error after the if statement.

**Comment by jackc** [comment]
Should be fixed now. The problem was with non-null values not null values.
