### ISSUE TITLE
Numeric Infinity & -Infinity Support

### ISSUE THREAD

**Issue by jimtsao** [jackc/pgtype#134]
Just wondering if there are any plans to support +/-infinity values for the Numeric type?

It's supported by timestamp(tz) and date types so far. Are there any particular reasons why it's not at the moment, or would we be open for a pull request to add in this functionality?

**Comment by jackc** [comment]
> Are there any particular reasons why it's not at the moment

It was just added to PG 14 one month ago. No one has gotten around to it yet.

> would we be open for a pull request to add in this functionality?

Definitely!

**Comment by jimtsao** [comment]
No worries. I'll take a look at it over the weekend.
