### ISSUE TITLE
Mock pgtype for testing

### ISSUE THREAD

**Issue by mathiasHillmann** [jackc/pgtype#135]
I have the function `coolFunction(arg1 coolStruct)` of which the `coolStruct` is composed of the following fields:
```
type coolStruct struct {
	id    pgtype.Int4
        foo   pgtype.Numeric
	name  pgtype.Text
}
```
How can I assign value to the `pgtype.*` fields for testing?

**Comment by jackc** [comment]
All the fields are public. You can directly initialize them. e.g. `s.id = pgtype.Int4{Int: 42, Status: pgtype.Present}` or use the `Set` method.
