### ISSUE TITLE
Encrypted types

### ISSUE THREAD

**Issue by benja-M-1** [jackc/pgtype#137]
Hi, 

I am looking for a way to encrypt the data my application is persisting. For now I plan to create custom types that decorates pgtypes and add the ability to encrypt/decrypt the value. It is the way I did on another project in another language. I was wondering if there was an existing solution that I was missing or if there was a better way.

Thanks for your answer.

**Comment by jackc** [comment]
There's no built-in encryption support in pgx / pgtype and I don't know of any libraries specifically designed for encrypted data in the database.

I have no idea whether handling your encryption needs at this layer is a good idea architecturally for your project, but assuming it is, your idea of wrapper / custom types doing the encryption should work.

**Comment by benja-M-1** [comment]
How would you do it if you had to?

**Comment by jackc** [comment]
I'd probably wrap the pgtype with a new type that implemented `BinaryDecoder` + `BinaryEncoder` and / or `TextDecoder` + `TextEncoder`.  Those functions would handle the encryption and decryption then delegate to the underlying type.

**Comment by benja-M-1** [comment]
Thank you @jackc for your answer! I am closing since it is not an issue :)
