### ISSUE TITLE
Breaking changes in v1.9.0 for decoding timestamp

### ISSUE THREAD

**Issue by condorcet** [jackc/pgtype#138]
Hello!
It seems that last changes for binary decoding of timestamp has broke backward compatibility.
In version 1.9.0 `time.Time` has local timezone after decoding timestamp.
I think it because of missing `UTC()` here https://github.com/jackc/pgtype/commit/5cb98120c10c0ed3125786007d6c0861d34b8f79#diff-1aef962e6259426c493d2499a5f85405d51a760644acdc53a9e51e0fbbf7b5ccR144

**Comment by jackc** [comment]
Good catch. Fixed.
