### ISSUE TITLE
Composite array not able to assignTo KSUID

### ISSUE THREAD

**Issue by davidspiess** [jackc/pgtype#142]
We use [KSUID ](https://github.com/segmentio/ksuid) instead of an `UUID` data type and i ran into an issue when decoding it from a composite type.
In the database we store it as `char(27)` but the underlying data type of a `KSUID` is `[20]bye`.
In the example below `.AssignTo` tries to convert the decoded `VarcharOID` to an integer and fails during this process.
Any idea how this could be prevented?

```go
type exampleCompositeType []struct {
	ID   ksuid.KSUID `json:"id"`
	Name string      `json:"name"`
}

func (pc *exampleCompositeType) DecodeText(ci *pgtype.ConnInfo, src []byte) error {
	dec := pgtype.NewArrayType("example_array", 0, func() pgtype.ValueTranscoder {
		ex, err := pgtype.NewCompositeType("example", []pgtype.CompositeTypeField{
			{OID: pgtype.VarcharOID}, {OID: pgtype.VarcharOID}}, ci)
		if err != nil {
			return nil
		}

		return ex
	})

	err := dec.DecodeText(ci, src)
	if err != nil {
		return err
	}

	err = dec.AssignTo(pc)
	if err != nil {
                // Throws integer conversion error 
		return err
	}

	return nil
}
```

**Comment by jackc** [comment]
I'm not sure all that's going on here but it would be much easier to build the single value type before building the array type. And with `NewArrayType` you shouldn't have to manually create the array type at all.

**Comment by davidspiess** [comment]
Thank you for the insights and your time looking into this. I will try to overhaul my code as you suggested!
