### ISSUE TITLE
time.Time for OID=1083 (time) fails with error "cannot convert %v to Text"

### ISSUE THREAD

**Issue by yuliyan-rhyme** [jackc/pgtype#15]
I'm having a column "start_at time not null" which SQLBoiler converts to go structure as "StartAt time.Time"

Query looks like:
INSERT INTO "my_table" ("id","start_at") VALUES ($1,$2)

where $1 = '74f6924b-98cb-4871-bf8d-962d7c8d0191' and $2 is time.Time (time.Now())

Running the query (via SQLBoiler) returns error: 
cannot convert 2019-12-09 02:00:00 +0200 EET to Text

I've followed the code and find out that the error is returned inside method: 

```golang
pgtype/text.go: Set(src interface{}) error
...
return errors.Errorf("cannot convert %v to Text", value)
```

It seems that for this OID=1083 (time) there is no appropriate function. I would expect the time.Time object for this OID type to look something like:

```golang
case time.Time:
	if value.IsZero() {
		*dst = Text{Status: Null}
	} else {
		*dst = Text{String: value.Format("15:04:05.00000"), Status: Present}
	}
```

If I hack the generic implementation in the pgtype/text.go, then the Insert statement succeed.

The only place where I saw time Format method is in pgtype/date.go, where we have:

```golang
s = src.Time.Format("2006-01-02")
```

Am I doing something wrong here or time type is not supported?

**Comment by jackc** [comment]
The time type wasn't directly supported. It's a bit tricky because PostgreSQL time supports the value `24:00:00`. But `time.Time` will normalize that to `00:00:00` the next day. It should work now if you update to master on pgtype.
