### ISSUE TITLE
pgtype.Int2 doesn't have any UnmarshalJSON

### ISSUE THREAD

**Issue by BigBoulard** [jackc/pgtype#153]
Hi guys,

We've noticed that the pgtype.Int2 doesn't have any UnmarshalJSON func but other int pgtypes does ( reference here: https://stackoverflow.com/questions/71862263/go-dynamic-update-queries-with-gin-and-pgx )

Many thanks

**Comment by jackc** [comment]
There's never been a concerted effort to add JSON to (un)marshaling to every type. It's been more on a as needed basis.

Just added it to pgtype.Int2.
