### ISSUE TITLE
Unmarshalling JSON null sets status to "Present"

### ISSUE THREAD

**Issue by freb** [jackc/pgtype#16]
I'm using LISTEN to get some streaming updates from Postgres in json format. The struct I'm unmarshalling into has two `pgtype.Int4` fields. The source JSON has one value set to `null` and the other value set to `2`. The result looked like this:

```
TaskID:{Int:2 Status:2}
TestID:{Int:0 Status:2}
```

Status of 2 is `Present` and it looks like `Present` is hardcoded in [UnmarshalJSON](https://github.com/jackc/pgtype/blob/a8802b16cc593842f5c69b0f7cfb0de11d5cd3a8/int4.go#L210).

I expected the result to look like this instead:

```
TaskID:{Int:2 Status:2}
TestID:{Int:0 Status:1}
```

where `1` is `Null`.

I changed the `UnmarshallJSON` function to the following and it achieves what I needed:

```go
func (dst *Int4) UnmarshalJSON(b []byte) error {
	var n *int32
	err := json.Unmarshal(b, &n)
	if err != nil {
		return err
	}

	if n == nil {
		*dst = Int4{Status: Null}
	} else {
		*dst = Int4{Int: *n, Status: Present}
	}

	return nil
}
```

Does this change make sense to you, and if so would you accept a PR for this? The change would cover all types of course, not just Int4.

**Comment by jackc** [comment]
That seems like a reasonable fix.
