### ISSUE TITLE
cannot encode status undefined

### ISSUE THREAD

**Issue by maximilian256** [jackc/pgtype#163]
I use a ```pgtype.JSON``` type in one of my struct field,  when i insert a value with status pgtype.NULL, everything works fine.
but when i retrive the same record into struct, the value's staus turns out to be pgtype.Undefined, can anyone explain this?
I think the status should be pgtype.Null as well but it is not.

**Comment by jackc** [comment]
I would expect that as well. But it is hard to tell without code. Can you make a short reproduction case?

**Comment by maximilian256** [comment]
Hi, thanks for your reply :). Here is a short snippet for what i did:

1.  Define a model contains ``` pgtype.JSON ```, which corresponds to my database type ```json```
```
type Employee struct {
	gorm.Model
	Attr pgtype.JSON `gorm:"column:attr"`
}
```
2. Insert a record using gorm. The ```Attr``` field was initialized with a ```pgtype.JSON```  whose status was assigned to ```pgtype.NULL``` explicitly by me.
```
employeeToInsert := &Employee{
		Model: gorm.Model{
			ID: 1,
		},
		Attr: pgtype.JSON{Status: pgtype.Null},
	}
	_ = db.Create(employeeToInsert)
```
The attr column of record inserted is NULL in database, which looks fine to me.

3. Retrive the same record just inserted
```
employeeInserted := new(Employee)
_ = db.Where("id = ?", "1").First(employeeInserted)
fmt.Println(employeeInserted.Attr.Status)
```
The result of Println is ```0```, which is pgtype.Undefined. 
It looks weired to me since when trying to update the same record fetched, it errors with the issue title.
Maybe i did it in a wrong way?

**Comment by jackc** [comment]
My guess it there is some incompatibility somewhere with gorm.

Directly selecting a `NULL` `json` value from PostgreSQL works as expected.

```go
package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	"github.com/jackc/pgtype"
	_ "github.com/jackc/pgx/v4/stdlib"
)

func main() {
	db, err := sql.Open("pgx", os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatalln(err)
	}
	defer db.Close()

	var j pgtype.JSON

	err = db.QueryRow(`select null::json`).Scan(&j)
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println(j.Status == pgtype.Null)
}
```

Prints: `true`

I don't have any experience with gorm, but my guess is you probably can sidestep the entire issue by using a `[]byte` instead of `pgtype.JSON`.
