### ISSUE TITLE
Known vulnerability in outdated pgx dependency, pgproto3-1.1.0

### ISSUE THREAD

**Issue by VitruvianVice** [jackc/pgtype#182]
The latest version of pgtype, [1.12.0](https://github.com/jackc/pgtype/releases/tag/v1.12.0), relies on an outdated version of pgx, version [4.12](https://github.com/jackc/pgx/releases/tag/v4.12.0). It uses the pgproto3 v1.1.0.

 The latest stable pgx version is [4.17](https://github.com/jackc/pgx/releases/tag/v4.17.0), with pgproto3 v2.3.1

 The Sonatype OSS Index determines the former version of pgproto to [contain a "medium" grave vulnerability](https://ossindex.sonatype.org/vulnerability/sonatype-2021-4807?component-type=golang&component-name=github.com%2Fjackc%2Fpgproto3&utm_source=nancy-client&utm_medium=integration&utm_content=1.0.33) due to unrestricted resource consumption.
 
 This seems to be resolvable by upgrading pgx to a more recent version.

**Comment by jackc** [comment]
> The Sonatype OSS Index determines the former version of pgproto to [contain a "medium" grave vulnerability](https://ossindex.sonatype.org/vulnerability/sonatype-2021-4807?component-type=golang&component-name=github.com%2Fjackc%2Fpgproto3&utm_source=nancy-client&utm_medium=integration&utm_content=1.0.33) due to unrestricted resource consumption.

It's a false alarm. It appears the "Sonatype OSS Index" does not distinguish between test and non-test dependencies. pgtype only uses pgx in tests.

> This seems to be resolvable by upgrading pgx to a more recent version.

If this vulnerability scanner has the same flaws as others it won't be satisfied. pgx depends on pgtype and pgtype's **tests** depend on pgx. This causes problems for scanners that naively follow the test dependency chain. See https://github.com/jackc/pgx/issues/1052 for more info.

**Comment by VitruvianVice** [comment]
I see. Looking closer at it I can confirm that you're absolutely right!
Thank you for pointing that out!
Also thanks for your work!

I'll close the issue!
