### ISSUE TITLE
modules imported with go 1.14

### ISSUE THREAD

**Issue by volkmarbuehringer** [jackc/pgtype#19]
if I import pgtype:
"github.com/jackc/pgx/pgtype"

in my source code

with go 1.14
I get the following modules in my go.mod file;

require (
	github.com/jackc/pgx v3.6.2+incompatible
	github.com/jackc/pgx/v4 v4.4.1

if I do 

go get github.com/jackc/pgx/pgtype

the output is:

go: found github.com/jackc/pgx/pgtype in github.com/jackc/pgx v3.6.2+incompatible

**Comment by jackc** [comment]
That is the pgtype for `v3`. Import `github.com/jackc/pgtype` instead.
