### ISSUE TITLE
BC Dates cause errors for the pgdate scanner

### ISSUE THREAD

**Issue by masterkidan** [jackc/pgtype#193]
It looks like pgdate type doesn't handle BC types well. When trying to parse these, we get the following error: 
`parsing time "0001-01-01 BC": extra text: " BC"`

**Comment by masterkidan** [comment]
#192 Addresses this issue, would appreciate some reviews here.

**Comment by masterkidan** [comment]
Looks like #192 is now merged, @jackc would it be possible to get a release with that fix?

**Comment by jackc** [comment]
Just tagged `v.1.13.0`.
