### ISSUE TITLE
Json marshaling and unmarshaling of pgtype.inet

### ISSUE THREAD

**Issue by dan-sherwin** [jackc/pgtype#194]
I’m using pgtype.inet in my struct. When I marshal the struct to Json I get the whole object definition of it. Is there anyway to just get a string representation of it without having to manually to it, create a new struct with that field of type string and then marshal that?  I know I can do it that way if needed but I was wondering if I was missing something on how that would marshal to a string automatically. And unmarshaling as well.

**Comment by jackc** [comment]
I presume you are using pgx v4? The problem is `pgtype.Inet` doesn't implement `json.Marshaller`. No reason it shouldn't, just no one has done it.

In pgx v5, `pgtype.Inet` is removed. `net.IP` or `netip.Addr` should be used directly. Presumably, those would marshal to JSON in the form you want.

**Comment by dan-sherwin** [comment]
In fact I was using v4.  I will move to v5.  Thanks for the heads up.
