### ISSUE TITLE
Release 1.14.3

### ISSUE THREAD

**Issue by graineri** [jackc/pgtype#214]
Would it be possible to release v1.14.3 with `pgconn v1.14.3`? 
That version has an up-to-date version of `pgproto3` that fixes a high vulnerability (https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMJACKCPGPROTO3V2-6371508)

**Comment by jackc** [comment]
Done. Though yet again Snyk is complaining about something that is inapplicable. ☹️
