### ISSUE TITLE
The "time with time zone" data type doesn't seem to be supported.

### ISSUE THREAD

**Issue by vnicolici** [jackc/pgtype#218]
I had a "time with time zone" column in the database, and of course I couldn't just map it to Go's time.Time. So I tried using pgtype.Time instead. This kind of worked, but not quite.

My database currently has a local time of UTC+3. I had a value in that column set to 15:05 local time (12:05 UTC). It was showing in PgAdmin as "15:05:00+03:00"

In the application reading from the database, the default time zone is set to US/Eastern. Currently that means UTC-04. So, that 15:05+03 should have been read as 08:05-04 in the application.

What actually happened when reading is that I got a value of 54,300,030,000 in the Microseconds field from pgtype.Time.
That means 54300 seconds, which is 905 minutes, so 15:05 hours since midnight. So, the read time was neither application time nor UTC time, but database server time instead. Furthermore, there were were an additional 0.03 seconds included.

I'm guessing what is happening is that the pgtype code gets the 15:05:00+03:00 string from the database, and parses it as 15:05:00.0300, so those 0.03 seconds are actually the 3 hours representing the UTC offset of the server time.

In the end, I switched that column from "time with time zone" to "time without time zone", which fixed the .03 seconds offset issue, and now I just assume in the application backend, and in the UI, that the column represents the local application time (US/Eastern).

Not sure how complicated it would be to support "time with time zone" as well, in addition to "time without time zone", maybe as a separate pgtype. It's not a big issue, at least if you have control over the database structure and you can change it. But, if it's not too complicated to implement, it would be nice to have support for this PostgreSQL type too.

**Comment by jackc** [comment]
This package is only receiving bug fixes. In pgx v5 the pgtype library is part of the main repo. But regardless, timestamp with time zone is unlikely to be supported. See https://github.com/jackc/pgx/issues/1940 for previous discussion.

**Comment by vnicolici** [comment]
All right, no problem, after reading a few related bugs and the PostgreSQL documentation it's clear the use of this data type is not recommended, and there are good reasons for that. So it's actually a good thing I had to switch to "time without time zone", and I'm fine with this data type not being supported.

In fact I remember reading about this data type not being recommended a few years ago. But when working on a new feature recently, I missed that part in the PostgreSQL documentation, even though I was specifically looking for that language discouraging its use, so I assumed it is OK to use it. In retrospect, after reading more about how that data type works, it wasn't clearly NOT OK. Daylight savings would have caused a huge mess if I kept using it.

However, I think that the documentation for pgtype.Time should make it clear that the "time with time zone" datatype is not not supported, and that its usage is not recommended by PostgreSQL. Even the pgx v5 documentation doesn't mention that.

**Comment by jackc** [comment]
> However, I think that the documentation for pgtype.Time should make it clear that the "time with time zone" datatype is not not supported, and that its usage is not recommended by PostgreSQL. Even the pgx v5 documentation doesn't mention that.

Fair enough.

https://github.com/jackc/pgx/commit/a68e14fe5ad7caed8657816b9883ed418f3324ec
