### ISSUE TITLE
Tstzrange bug when querying with contains operator

### ISSUE THREAD

**Issue by feketegy** [jackc/pgtype#22]
I have this query, where validity is of tstzrange type:

    SELECT
        id
    FROM
        my_list
    WHERE
        validity @> $1
    LIMIT 1
    ;

    tDate := time.Now()
    var id int
    err = tx.QueryRow(
        p.ctx,
	tDate,
	).Scan(
	    &id,
	)

The following code throws an error: cannot convert 2020-04-04 16:03:06.679 +0000 UTC to Tstzrange

The validity column is a tstzrange, but the sql query above works fine when I test it directly in Postgresql. `validity @> $1` accepts a timestamptz like `validity @> '2020-04-04 00:00:00.000+00'::timestamptz`

When I try to set a time.Time for $1, pgtype wants to convert it to a tstzrange, even though it shouldn't.

**Comment by jackc** [comment]
You may need to be explicit with the type in the SQL. Try this SQL: 

```sql
SELECT
    id
FROM
    my_list
WHERE
    validity @> $1::timestamptz
LIMIT 1
;
```

**Comment by feketegy** [comment]
Did the trick, thanks!

Though shouldn't this be handled in pgtype? 

I mean if using a timestamptz (translates to time.Time in Go) in the sql query above, Postgresql doesn't complains to convert it to timestamptz.

**Comment by jackc** [comment]
`pgtype` can't do anything about this. It is a because `pgx` is implicitly using prepared statements. The same issue occurs in `psql` when using prepared statements.

```
jack@[local:/private/tmp]:5432 pgx_issues=# create table t (
pgx_issues(#   id int primary key generated by default as identity,
pgx_issues(#   color text not null,
pgx_issues(#   validity tstzrange not null
pgx_issues(# );
CREATE TABLE
Time: 5.448 ms
jack@[local:/private/tmp]:5432 pgx_issues=# insert into t(color, validity) values ('green', '[2020-01-01,2020-03-01)'), ('blue', '[2020-03-01,)');
INSERT 0 2
Time: 1.112 ms
jack@[local:/private/tmp]:5432 pgx_issues=# prepare s as select id from t where validity @> $1 limit 1;
PREPARE
Time: 0.604 ms
jack@[local:/private/tmp]:5432 pgx_issues=# execute s('2020-02-01 00:00:00');
ERROR:  malformed range literal: "2020-02-01 00:00:00"
LINE 1: execute s('2020-02-01 00:00:00');
                  ^
DETAIL:  Missing left parenthesis or bracket.
Time: 0.337 ms
```
The type is determined at prepare time. By the time `pgtype` is encoding the time.Time value it is too late -- the server is already expecting a `tstzrange`.

...

Actually, it's not just prepared statements. I just noticed in your original post that you are using `::timestamptz` in your working example with a literal `timestamptz`. The same ambiguity must be resolved using the simple protocol in `psql`.

```
jack@[local:/private/tmp]:5432 pgx_issues=# select id from t where validity @> '2020-02-01 00:00:00';
ERROR:  malformed range literal: "2020-02-01 00:00:00"
LINE 1: select id from t where validity @> '2020-02-01 00:00:00';
                                           ^
DETAIL:  Missing left parenthesis or bracket.
Time: 0.270 ms
```
