### ISSUE TITLE
github.com/jackc/pgproto3 SQL injection 

### ISSUE THREAD

**Issue by konstantin-nizhinskiy** [jackc/pgtype#221]
https://github.com/jackc/pgx/issues/2144#issue-2570789851

update dependency please
github.com/jackc/pgx/v4 v4.18.2

to 

github.com/jackc/pgx/v4 v4.18.3

**Comment by jackc** [comment]
🤷 v4.18.2 has the fix as well. But I just bumped the dependency. Maybe this will make those broken dependency scanners stop complaining.
