### ISSUE TITLE
[DOUBT] adding 1 byte to jsonb null value?

### ISSUE THREAD

**Issue by Streppel** [jackc/pgtype#25]
While reading the source code I encountered the following line

https://github.com/jackc/pgtype/blob/98c9ec4f7b4b3870ae0cc3fbfb35cb5c7798f5d9/jsonb.go#L58

I'd like to understand what is the purpose of it, as it smells a bit buggy to me. Is this correct? The returned value ends up being, for nil values, a byte slice containing the following, which is not the same for the json type for example

0 = {uint8} 1
1 = {uint8} 110
2 = {uint8} 117
3 = {uint8} 108
4 = {uint8} 108

**Comment by jackc** [comment]
JSONB binary format is prefixed with version number -- which is currently always `1`.

See https://github.com/postgres/postgres/blob/3436c5e28374d4e0587634fda09faf4a38a9d848/src/backend/utils/adt/jsonb.c#L105.

**Comment by Streppel** [comment]
I see! I didn't know about that, that's super interesting. Thanks!
