### ISSUE TITLE
How do you check if pgtype.Text is null?

### ISSUE THREAD

**Issue by sk0g** [jackc/pgtype#34]
Hi, so I'm trying to accomplish the above, and this is what I'm trying at the moment:

I have a struct declaration
```go
import (
	"github.com/jackc/pgx/pgtype"
)

type ABC struct {
        ...
	Address     pgtype.Text        `db:"address"`
        ...
}
```

And I'm trying to check if the field is null
```go
import (
	"strings"

	"github.com/jackc/pgtype"
)

if abc.Address.Status == pgtype.Null { }
```

However, it gives me the following error
```
invalid operation: abc.Address.Status == "github.com/jackc/pgtype".Null (mismatched types "github.com/jackc/pgx/pgtype".Status and "github.com/jackc/pgtype".Status)
```

At no point is `pgx/pgtype` imported, so how would I check if something is null?

Speaking of, would a function for each data type, `IsNull()` or `IsPresent()` be of value? I was surprised to see nothing of the sort, though I'm not sure if it would be implementable without major pains.

Cheers!

**Comment by jackc** [comment]
This appears to be caused by import confusion.

`github.com/jackc/pgtype`
vs
`github.com/jackc/pgx/pgtype`.

With pgx v4 you want to use `github.com/jackc/pgtype`. As far as a helper method you can use `Get()`. It will return `nil` for a database `NULL`.

**Comment by sk0g** [comment]
Ah man, I double checked the imports about 5 times too, since I was copy pasting them in, and still didn't catch it!

I take it `pgx/pgtype` is there for legacy reasons?

**Comment by jackc** [comment]
`pgtype` package was in a subdirectory of `pgx` until `v3`. As of `v4` it was split off to a separate repo to allow easier reuse and evolution.

**Comment by sk0g** [comment]
Makes sense, thank you :slightly_smiling_face:
