### ISSUE TITLE
interval with months or days cannot be decoded into *time.Duration

### ISSUE THREAD

**Issue by kwargs** [jackc/pgtype#42]
Hi I'm found that I can't assign `interval` with days or months to `time.Durartion`
```
interval with months or days cannot be decoded into *time.Duration
```

What were the reasons for doing this?

https://github.com/jackc/pgtype/blob/55a56add235573da4358e3fd52ad4a35b30c92eb/interval.go#L69
https://gist.github.com/kwargs/bc8498740bd271c9875ea3ca53337b4c

**Comment by jackc** [comment]
A duration is an `int64` of nanoseconds (https://golang.org/pkg/time/#Duration). The number of nanoseconds in a day or a month varies depending on the day or the month.

**Comment by kwargs** [comment]
>  The number of nanoseconds in a day or a month varies depending on the day or the month.

It's true when we work with `timestamps`, but `interval` with month has constant days count

```sql
> SELECT EXTRACT(epoch FROM interval '1 month') / (60 * 60 * 24) days_in_month;
 days_in_month
---------------
            30
(1 row)
```

**Comment by jackc** [comment]
Hmm... I don't like having conversions that are lossy. But I guess there is precedent for it here and we do allow a similar lossy conversion from numeric to float.
