### ISSUE TITLE
Scanning empty UUIDArray causes out of bounds access

### ISSUE THREAD

**Issue by tolfino** [jackc/pgtype#68]
Minimal example:

```go
import "github.com/google/uuid"

var t []uuid.UUID
tx.QueryRow(ctx, `select '{}'::uuid[]`).Scan(&t)  // panic: runtime error: index out of range [0] with length 0
```

It looks like `assignToRecursive` is always called with index = 0, dimension = 0, which then:

1. Breaks from the `reflect.Slice` case,
2. Indexes `src.Elements[0]` and panics.

I don't know what the best special case handling should be here: maybe an explicit check for an empty array? Do multidimensional empty arrays exist?

This is also likely not restricted to UUIDArray, it's just the type I tested with.

**Comment by jackc** [comment]
@haasanen Any ideas? I'm having trouble reasoning about this recursive reflection code.
