### ISSUE TITLE
pointer to slice seems to have stopped working after 1.3.0

### ISSUE THREAD

**Issue by PaulForgey** [jackc/pgtype#69]
attempting to scan into a pointer-to slice, in this case *[]string, results in the confusing error
`can't scan into dest[0]: incorrect dimensions, expected 1, found 0`

Because unlike the prior code, it does not re-attempt after a dereference of the destination.

Should this case work? scany depends on it in its tests to do so. There is, however, a distinction of nil vs. empty slices, but pointers to maps are still working.

**Comment by jackc** [comment]
It should be fixed now. The path that allocates a slice if necessary was never being called.

@haasanen This change affects the multi-dimension / reflection path, but as far as I can tell everything there still works.
