### ISSUE TITLE
Regression in the v1.5.0 release 

### ISSUE THREAD

**Issue by georgysavva** [jackc/pgtype#72]
Hi. There is a regression in v1.5.0 compared to v1.4.2
Here is the case:
```go
var dst *[]string
err = db.QueryRow(ctx, `SELECT ARRAY('foo val', 'foo val 2', 'foo val 3')`).Scan(&dst)
```
This returns an error:
```
can't scan into dest[0]: incorrect dimensions, expected 1, found 0
```
In v1.4.2 the above operation was successful. 
I guess it might be related to this change: https://github.com/jackc/pgtype/pull/51

**Comment by PaulForgey** [comment]
I think both of us found this - I've reported issue #69

**Comment by jackc** [comment]
> I think both of us found this - I've reported issue #69

Correct. This is the same issue. I'll respond on #69.
