### ISSUE TITLE
Tstzrange Panic Encode

### ISSUE THREAD

**Issue by AubSs** [jackc/pgtype#74]
Encode pgtype.Tstzrange with `[eeee,)`cause a panic.
=> `runtime error: index out of range [-5]`

shouldn't be reported as invalid tstzrange instead ?

**Comment by jackc** [comment]
> Encode pgtype.Tstzrange with [eeee,)cause a panic.

I presume you mean *decode*.

Underlying problem was with Timestamptz.DecodeText and is now fixed.
