### ISSUE TITLE
CopyFrom & NaN

### ISSUE THREAD

**Issue by thomascoquet** [jackc/pgtype#93]
Hello,
First of all, thank you a lot for `pgx` which is very robust and works incredibly well in our codebase!
I am using the `CopyFrom` feature to load data into a table, and I need to insert a NaN.

**PostgreSQL**: 12, **pgx**: latest

The postgres type is `NUMERIC(5, 2) NOT NULL`. We implemented the CopyFromSource interface (namely `Values() ([]interface{}, error)`).

To load the NaN, I first returned simply `math.NaN()` in the slice `[]interface{}` but it resulted in an error. I then tried:
```
myFloat := &pgtype.Numeric{}
myFloat.Set(math.NaN())
return []interface{}{..., myFloat, ...}
```

but obtained the same error, which is the following:

```
&pgconn.PgError{Severity:"ERROR", Code:"22P03", Message:"invalid sign in external \"numeric\" value", Detail:"", Hint:"", Position:0, InternalPosition:0, InternalQuery:"", Where:"COPY tmp_277d49fb10954eb9a5d29609e113648c, line 2, column cloud_cover_land", SchemaName:"", TableName:"", ColumnName:"", DataTypeName:"", ConstraintName:"", File:"numeric.c", Line:833, Routine:"numeric_recv"}
```

Am I doing something wrong?
Thanks, Thomas

**Comment by thomascoquet** [comment]
What is working for me is:
```
const (
	pgNumericNaN     = 0x00000000c0000000
	pgNumericNaNSign = 0xc000
)
```
with a uint for the sign: 
```
sign := uint16(binary.BigEndian.Uint16(src[rp:]))
```
Thomas

**Comment by jackc** [comment]
Ewww... turns out there were several problems with NaN handling and somehow it eluded the test suite. Should be fixed now.
