### ISSUE TITLE
Scan array of rows

### ISSUE THREAD

**Issue by pracj3am** [jackc/pgtype#98]
Hello I have the following query:
```
SELECT array_agg(ROW(a, b)) FROM ...
```
and I would like to scan the result into smth like `[]pgtype.Record`, but I get
```
unknown oid 2287 cannot be scanned into *[]pgtype.Record
```

Is there any simple solution to that? I am able to scan a single row like in [record_test.go](https://github.com/jackc/pgtype/blob/master/record_test.go), but I can't figure out, how to do the same with the array of rows.

**Comment by jackc** [comment]
There's no support for scanning into `[]pgtype.Record` directly out of the box. You could probably use `pgtype.ArrayType` though.

**Comment by pracj3am** [comment]
Thanks for reply
